import type { Meta, StoryObj } from "@storybook/react";
import { HomepageFilter } from "./HomepageFilter";

const meta = {
  title: "Molecules/HomepageFilter",
  component: HomepageFilter,
  tags: ["autodocs"],
} satisfies Meta<typeof HomepageFilter>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    offers: [
      {
        id: 1,
        title: "The Fellowship of the Ring",
        author: "J.R.R. Tolkien",
        image: {
          src: "https://cdn.kobo.com/book-images/7a557cb3-f72a-47c3-992b-951c9566e4d4/1200/1200/False/the-fellowship-of-the-ring-the-lord-of-the-rings-book-1-1.jpg",
          alt: "",
        },
        price: 10,
        condition: "Wie neu",
        tags: ["Fantasy"],
        language: "English",
        postCode: "10115",
        city: "Berlin",
        size: "small",
      },
      {
        id: 2,
        title: "Harry Potter and the Philosopher's Stone",
        author: "J.K. Rowling",
        image: {
          src: "https://i.etsystatic.com/19315611/r/il/9e9295/3517997038/il_500x500.3517997038_5t41.jpg",
          alt: "Harry Potter 1",
        },
        price: 8,
        condition: "Gebraucht",
        tags: ["Fantasy"],
        language: "Deutsch",
        postCode: "20095",
        city: "Hamburg",
        size: "small",
      },
      {
        id: 3,
        title: "Der Vorleser",
        author: "Bernhard Schlink",
        image: {
          src: "https://tse4.mm.bing.net/th/id/OIP.2uqhVxjVp_cvvusUMFG7WAHaLz?pid=Api",
          alt: "Der Vorleser",
        },
        price: 6,
        condition: "Leichte Gebrauchsspuren",
        tags: ["Drama"],
        language: "Deutsch",
        postCode: "50667",
        city: "Köln",
        size: "small",
      },
      {
        id: 4,
        title: "1984",
        author: "George Orwell",
        image: {
          src: "https://tse4.mm.bing.net/th/id/OIP.g8s4n-puPV3y-F2b7ilJ_AHaJ1?pid=Api",
          alt: "1984",
        },
        price: 5,
        condition: "Gebraucht",
        tags: ["Dystopia"],
        language: "English",
        postCode: "80331",
        city: "München",
        size: "small",
      },
      {
        id: 5,
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        image: {
          src: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1651074858i/60892816.jpg",
          alt: "Subtle Art",
        },
        price: 12,
        condition: "Wie neu",
        tags: ["Self-help"],
        language: "English",
        postCode: "70173",
        city: "Stuttgart",
        size: "small",
      },
      {
        id: 6,
        title: "Clean Code",
        author: "Robert C. Martin",
        image: {
          src: "https://tse3.mm.bing.net/th/id/OIP.ZfYHb383Tk0kUMP-XsfWegHaJI?pid=Api",
          alt: "Clean Code",
        },
        price: 25,
        condition: "Wie neu",
        tags: ["Programming"],
        language: "English",
        postCode: "01067",
        city: "Dresden",
        size: "small",
      },
      {
        id: 7,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        image: {
          src: "https://tse1.mm.bing.net/th/id/OIP.xOjvBsPCYVmiG-wCavUpPQHaLR?pid=Api",
          alt: "Sapiens",
        },
        price: 15,
        condition: "Leichte Gebrauchsspuren",
        tags: ["History"],
        language: "English",
        postCode: "90403",
        city: "Nürnberg",
        size: "small",
      },
      {
        id: 8,
        title: "Der Alchimist",
        author: "Paulo Coelho",
        image: {
          src: "https://tse2.mm.bing.net/th/id/OIP.TmpYLY8VfadRn7A53xVxawHaLt?pid=Api",
          alt: "Der Alchimist",
        },
        price: 7,
        condition: "Gebraucht",
        tags: ["Philosophy"],
        language: "Deutsch",
        postCode: "34117",
        city: "Kassel",
        size: "small",
      },
      {
        id: 9,
        title: "Dune",
        author: "Frank Herbert",
        image: {
          src: "https://tse2.mm.bing.net/th/id/OIP.cvoSdGRO8TtT-zw5N0qAAQHaLL?pid=Api",
          alt: "Dune",
        },
        price: 11,
        condition: "Wie neu",
        tags: ["Sci-Fi"],
        language: "English",
        postCode: "28195",
        city: "Bremen",
        size: "small",
      },
      {
        id: 10,
        title: "Die Physiker",
        author: "Friedrich Dürrenmatt",
        image: {
          src: "https://i.pinimg.com/736x/b0/8d/69/b08d699f26fd92b3338dc9a61f58eeaf--die-physiker-friedrich-d%C3%BCrrenmatt.jpg",
          alt: "Die Physiker",
        },
        price: 4,
        condition: "Gebraucht",
        tags: ["Drama"],
        language: "Deutsch",
        postCode: "86150",
        city: "Augsburg",
        size: "small",
      },
      {
        id: 11,
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt & David Thomas",
        image: {
          src: "https://tse2.mm.bing.net/th/id/OIP.KI_tsGHe4sBa0xd3WjpMyQHaJs?pid=Api",
          alt: "Pragmatic Programmer",
        },
        price: 22,
        condition: "Wie neu",
        tags: ["Programming"],
        language: "English",
        postCode: "44135",
        city: "Dortmund",
        size: "small",
      },
      {
        id: 12,
        title: "Momo",
        author: "Michael Ende",
        image: {
          src: "https://tse4.mm.bing.net/th/id/OIP.I1ojrOw5PDlZZ-t66bTsOQHaLr?pid=Api",
          alt: "Momo",
        },
        price: 5,
        condition: "Leichte Gebrauchsspuren",
        tags: ["Fantasy"],
        language: "Deutsch",
        postCode: "97070",
        city: "Würzburg",
        size: "small",
      },
    ],
  },
};
