import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OnlyBooks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-blue-600 p-4">
          <ul className="flex space-x-6 font-medium text-lg text-white">
            <li>
              <Link href="/" className="transition-colors duration-200 hover:text-blue-200">
                Home
              </Link>
            </li>
            <li>
              <Link href="route-a" className="transition-colors duration-200 hover:text-blue-200">
                RouteA
              </Link>
            </li>
            <li>
              <Link href="route-b" className="transition-colors duration-200 hover:text-blue-200">
                RouteB
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
